stages:
    - build

build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    only: 
        - master
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
        - docker build -t registry.gitlab.com/xagakure-b2/dotnet:latest .
        - docker push registry.gitlab.com/xagakure-b2/dotnet:latest